#!/bin/bash
if [ -z $LD_LIBRARY_PATH ]; then
LD_LIBRARY_PATH=$HOME/.local/lib
export LD_LIBRARY_PATH=$HOME/.local/lib
echo 'LD_LIBRARY_PATH=$HOME/.local/lib/' >> $HOME/.bashrc
echo 'export LD_LIBRARY_PATH=$HOME/.local/lib/' >> $HOME/.bashrc
fi
if [ -z $PKG_CONFIG_PATH ]; then
PKG_CONFIG_PATH=$HOME/.local/lib/pkconfig/
export PKG_CONFIG_PATH=$HOME/.local/lib/pkconfig/
echo 'PKG_CONFIG_PATH=$HOME/.local/lib/pkconfig/' >> $HOME/.bashrc
echo 'export PKG_CONFIG_PATH=$HOME/.local/lib/pkconfig/' >> $HOME/.bashrc
fi
patchcheck="$(echo $PATH|grep $HOME/.local/bin)"
if [ -z $patchcheck ]; then
PATH=$PATH:$HOME/.local/bin/
export PATH=$PATH:$HOME/.local/bin/
echo 'PATH=$PATH:$HOME/.local/bin/' >> $HOME/.bashrc
echo 'export PATH=$PATH:$HOME/.local/bin/' >> $HOME/.bashrc
fi
rm -rf $HOME/.local/etc/apt/
mkdir -p $HOME/.local/var/lib/apt/lists/partial/
mkdir -p $HOME/.local/etc/apt/preferences.d/
mkdir -p $HOME/.local/etc/apt/trusted.gpg.d/
mkdir -p $HOME/.local/etc/apt/sources.list.d/
mkdir -p $HOME/.local/var/cache/apt/archives/partial
cp /etc/apt/trusted.gpg.d/* $HOME/.local/etc/apt/trusted.gpg.d/
cp /etc/apt/sources.list.d/* $HOME/.local/etc/apt/sources.list.d/
cp /etc/apt/sources.list $HOME/.local/etc/apt/
apt-config dump > $HOME/.local/etc/apt/apt.conf
sed -i "s|Dir \"/\";|Dir \"$HOME/.local\";|" $HOME/.local/etc/apt/apt.conf
sed -i "s|Dir::Bin::dpkg \"/usr/bin/dpkg\";|Dir::Bin::dpkg \"$HOME/.local/bin/dpkg-local\";|" $HOME/.local/etc/apt/apt.conf
sed -i "s|Dir::State::status \"/var/lib/dpkg/status\";|Dir::State::status \"$HOME/.local/var/lib/dpkg/status\";|" $HOME/.local/etc/apt/apt.conf
mkdir -p $HOME/.local/bin
mkdir -p $HOME/.local/var/lib/dpkg/alternatives
cp -R /var/lib/dpkg/alternatives/* $HOME/.local/var/lib/dpkg/alternatives/
cp /var/lib/dpkg/arch $HOME/.local/var/lib/dpkg/
cp /var/lib/dpkg/available $HOME/.local/var/lib/dpkg/
cp /var/lib/dpkg/cmethopt $HOME/.local/var/lib/dpkg/
cp /var/lib/dpkg/diversions $HOME/.local/var/lib/dpkg/
cp /var/lib/dpkg/diversions-old $HOME/.local/var/lib/dpkg/
mkdir -p $HOME/.local/var/lib/dpkg/info/
cp -R /var/lib/dpkg/info $HOME/.local/var/lib/dpkg/info/
touch $HOME/.local/var/lib/dpkg/lock
chmod 777 $HOME/.local/var/lib/dpkg/lock
touch $HOME/.local/var/lib/dpkg/lock-frontend
chmod 777 $HOME/.local/var/lib/dpkg/lock-frontend
mkdir -p $HOME/.local/var/lib/dpkg/parts
cp /var/lib/dpkg/statoverride $HOME/.local/var/lib/dpkg/
cp /var/lib/dpkg/statoverride-old $HOME/.local/var/lib/dpkg/
if [ -f $HOME/.local/var/lib/dpkg/status ]; then
   cp /var/lib/dpkg/status $HOME/.local/var/lib/dpkg/
   cp /var/lib/dpkg/status-old $HOME/.local/var/lib/dpkg/
fi
touch $HOME/.local/var/lib/dpkg/updates
chmod 777 $HOME/.local/var/lib/dpkg/updates
mkdir -p $HOME/.local/bin/
cat > $HOME/.local/bin/dpkg-local <<EOF
#!/bin/bash
if [ -z $LD_LIBRARY_PATH ]; then
LD_LIBRARY_PATH=$HOME/.local/lib
export LD_LIBRARY_PATH=$HOME/.local/lib
echo 'LD_LIBRARY_PATH=$HOME/.local/lib/' >> $HOME/.bashrc
echo 'export LD_LIBRARY_PATH=$HOME/.local/lib/' >> $HOME/.bashrc
fi
if [ -z $PKG_CONFIG_PATH ]; then
PKG_CONFIG_PATH=$HOME/.local/lib/pkconfig/
export PKG_CONFIG_PATH=$HOME/.local/lib/pkconfig/
echo 'PKG_CONFIG_PATH=$HOME/.local/lib/pkconfig/' >> $HOME/.bashrc
echo 'export PKG_CONFIG_PATH=$HOME/.local/lib/pkconfig/' >> $HOME/.bashrc
fi
/usr/bin/dpkg --admindir=$HOME/.local/var/lib/dpkg --force-not-root --root=$HOME/.local/ $@
mkdir -p $HOME/.local/usr/lib/
cp -R $HOME/.local/usr/lib/x86_64-linux-gnu/* $HOME/.local/usr/lib/
rm -rf $HOME/.local/usr/lib/x86_64-linux-gnu/
cp -R $HOME/.local/usr/* $HOME/.local/
rm -rf $HOME/.local/usr/
EOF
chmod +x $HOME/.local/bin/dpkg-local
/usr/bin/apt -c=$HOME/.local/etc/apt/apt.conf $@
